const LOGIN_DATA_INIT = 'LOGIN_DATA_INIT';
const LOGIN_DATA_SUCCESS = 'LOGIN_DATA_SUCCESS';
const LOGIN_DATA_ERROR = 'LOGIN_DATA_ERROR';

const GOOGLE_LOGIN_DATA_INIT = 'GOOGLE_LOGIN_DATA_INIT';
const GOOGLE_LOGIN_DATA_SUCCESS = 'GOOGLE_LOGIN_DATA_SUCCESS';
const GOOGLE_LOGIN_DATA_ERROR = 'GOOGLE_LOGIN_DATA_ERROR';

const REGISTER_INIT = 'REGISTER_INIT';
const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_ERROR = 'REGISTER_ERROR';

const FORGOT_PASSWORD_INIT = 'FORGOT_PASSWORD_INIT';
const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';

const CONTACT_US_INIT = 'CONTACT_US_INIT';
const CONTACT_US_SUCCESS = 'CONTACT_US_SUCCESS';
const CONTACT_US_ERROR = 'CONTACT_US_ERROR';

const TEAM_DATA_INIT = 'TEAM_DATA_INIT';
const TEAM_DATA_SUCCESS = 'TEAM_DATA_SUCCESS';
const TEAM_DATA_ERROR = 'TEAM_DATA_ERROR';

const NOTICES_DATA_INIT = 'NOTICES_DATA_INIT';
const NOTICES_DATA_SUCCESS = 'NOTICES_DATA_SUCCESS';
const NOTICES_DATA_ERROR = 'NOTICES_DATA_ERROR';

const MAGAZINE_DATA_INIT = 'MAGAZINE_DATA_INIT';
const MAGAZINE_DATA_SUCCESS = 'MAGAZINE_DATA_SUCCESS';
const MAGAZINE_DATA_ERROR = 'MAGAZINE_DATA_ERROR';

const MY_MAGAZINE_DATA_INIT = 'MY_MAGAZINE_DATA_INIT';
const MY_MAGAZINE_DATA_SUCCESS = 'MY_MAGAZINE_DATA_SUCCESS';
const MY_MAGAZINE_DATA_ERROR = 'MY_MAGAZINE_DATA_ERROR';

export {
  LOGIN_DATA_INIT,
  LOGIN_DATA_SUCCESS,
  LOGIN_DATA_ERROR,
  GOOGLE_LOGIN_DATA_INIT,
  GOOGLE_LOGIN_DATA_SUCCESS,
  GOOGLE_LOGIN_DATA_ERROR,
  REGISTER_INIT,
  REGISTER_SUCCESS,
  REGISTER_ERROR,
  FORGOT_PASSWORD_INIT,
  FORGOT_PASSWORD_SUCCESS,
  FORGOT_PASSWORD_ERROR,
  CONTACT_US_INIT,
  CONTACT_US_SUCCESS,
  CONTACT_US_ERROR,
  TEAM_DATA_INIT,
  TEAM_DATA_SUCCESS,
  TEAM_DATA_ERROR,
  NOTICES_DATA_INIT,
  NOTICES_DATA_SUCCESS,
  NOTICES_DATA_ERROR,
  MAGAZINE_DATA_INIT,
  MAGAZINE_DATA_SUCCESS,
  MAGAZINE_DATA_ERROR,
  MY_MAGAZINE_DATA_INIT,
  MY_MAGAZINE_DATA_SUCCESS,
  MY_MAGAZINE_DATA_ERROR,
};
