const LOGIN_DATA_INIT = 'LOGIN_DATA_INIT';
const LOGIN_DATA_SUCCESS = 'LOGIN_DATA_SUCCESS';
const LOGIN_DATA_ERROR = 'LOGIN_DATA_ERROR';

const REGISTER_INIT = 'REGISTER_INIT';
const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_ERROR = 'REGISTER_ERROR';

const MAGAZINE_DATA_INIT = 'MAGAZINE_DATA_INIT';
const MAGAZINE_DATA_SUCCESS = 'MAGAZINE_DATA_SUCCESS';
const MAGAZINE_DATA_ERROR = 'MAGAZINE_DATA_ERROR';

export {
  LOGIN_DATA_INIT,
  LOGIN_DATA_SUCCESS,
  LOGIN_DATA_ERROR,
  REGISTER_INIT,
  REGISTER_SUCCESS,
  REGISTER_ERROR,
  MAGAZINE_DATA_INIT,
  MAGAZINE_DATA_SUCCESS,
  MAGAZINE_DATA_ERROR,
};
