// CoronaAction
const GET_USER_DATA_INIT = 'GET_USER_DATA_INIT';
const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
const GET_USER_DATA_ERROR = 'GET_USER_DATA_ERROR';

export { GET_USER_DATA_INIT, GET_USER_DATA_SUCCESS, GET_USER_DATA_ERROR };
